name: vibrio_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abricate=0.7
  - argtable2=2.13
  - bedtools=2.31.1
  - biopython=1.86
  - blast=2.16.0
  - blast-legacy=2.2.26
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bwa=0.7.18
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - cgecore=2.0.1
  - cgelib=0.7.5
  - checkm-genome=1.2.4
  - circos=0.69.9
  - clustalo=1.2.4
  - clustalw=2.1
  - consan=1.2
  - contourpy=1.3.3
  - curl=8.16.0
  - cycler=0.12.1
  - dendropy=5.0.8
  - dialign-tx=1.0.2
  - dnspython=2.8.0
  - emboss=6.6.0
  - entrez-direct=22.4
  - expat=2.7.1
  - famsa=2.2.3
  - fastqc=0.12.1
  - fasttree=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.12.1
  - gawk=5.3.1
  - git=2.45.1
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glimmerhmm=3.0.4
  - gmp=6.3.0
  - gsl=2.7
  - hmmer=3.4
  - icu=75.1
  - joblib=1.5.2
  - jpeg=9e
  - jq=1.8.1
  - k8=0.2.5
  - kalign2=2.04
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - kma=1.4.15
  - krb5=1.21.3
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcurl=8.16.0
  - libdb=6.2.32
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libharu=2.4.4
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - mafft=7.526
  - matplotlib-base=3.10.1
  - minimap2=2.28
  - mpfr=4.2.1
  - mpi=1.0
  - munkres=1.0.7
  - muscle=3.8.1551
  - mustang=3.2.4
  - ncbi-amrfinderplus=4.0.23
  - ncbi-datasets-cli=18.9.0
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - numpy=2.3.4
  - oniguruma=6.9.10
  - openjdk=11.0.1
  - openjpeg=2.4.0
  - openmpi=4.1.6
  - openssl=3.6.1
  - packaging=25.0
  - paml=4.10.9
  - pandas=2.3.3
  - pasta=1.9.2
  - patsy=1.0.2
  - pcre=8.45
  - pcre2=10.43
  - perl=5.32.1
  - perl-algorithm-diff=1.1903
  - perl-app-cpanminus=1.7048
  - perl-archive-tar=3.04
  - perl-b-cow=0.007
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-featureio=1.6.905
  - perl-bio-samtools=1.43
  - perl-bio-searchio-hmmer=1.7.3
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.8
  - perl-bioperl-core=1.7.8
  - perl-bioperl-run=1.007003
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-class-data-inheritable=0.09
  - perl-clone=0.46
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-config-general=2.67
  - perl-constant=1.33
  - perl-data-dumper=2.183
  - perl-db_file=1.858
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.05
  - perl-digest-md5=2.58
  - perl-digest-perl-md5=1.9
  - perl-encode=3.19
  - perl-encode-locale=1.05
  - perl-exception-class=1.45
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-listing=6.16
  - perl-file-slurp=9999.32
  - perl-file-slurper=0.014
  - perl-file-sort=1.01
  - perl-file-spec=3.48_01
  - perl-findbin=1.54
  - perl-font-ttf=1.06
  - perl-gd=2.76
  - perl-getopt-long=2.58
  - perl-html-parser=3.81
  - perl-html-tagset=3.24
  - perl-http-cookies=6.11
  - perl-http-daemon=6.16
  - perl-http-date=6.06
  - perl-http-message=7.01
  - perl-http-negotiate=6.01
  - perl-inc-latest=0.500
  - perl-io-compress=2.201
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.074
  - perl-io-string=1.08
  - perl-io-tty=1.16
  - perl-io-zlib=1.15
  - perl-ipc-run=20250809.0
  - perl-json=4.10
  - perl-json-xs=4.04
  - perl-libwww-perl=6.67
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-lwp-mediatypes=6.04
  - perl-lwp-simple=6.67
  - perl-math-bezier=0.01
  - perl-math-round=0.07
  - perl-math-vecstat=0.08
  - perl-mime-base64=3.16
  - perl-module-build=0.4234
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-net-http=6.24
  - perl-net-ssleay=1.92
  - perl-ntlm=1.09
  - perl-number-format=1.76
  - perl-params-validate=1.31
  - perl-parent=0.236
  - perl-pathtools=3.73
  - perl-readonly=2.05
  - perl-regexp-common=2017060201
  - perl-scalar-list-utils=1.62
  - perl-set-intspan=1.19
  - perl-socket=2.027
  - perl-statistics-basic=1.6611
  - perl-sub-uplevel=0.2800
  - perl-svg=2.87
  - perl-test-deep=1.130
  - perl-test-differences=0.69
  - perl-test-exception=0.43
  - perl-test-fatal=0.016
  - perl-test-harness=3.44
  - perl-test-more=1.001002
  - perl-test-most=0.38
  - perl-test-needs=0.002009
  - perl-test-warn=0.36
  - perl-text-csv=2.01
  - perl-text-diff=1.45
  - perl-text-format=0.63
  - perl-threaded=5.32.1
  - perl-time-hires=1.9764
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-tree-dag_node=1.35
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-uri=5.12
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-xpathengine=0.14
  - perl-yaml=1.30
  - phylip=3.697
  - pip=25.2
  - poa=2.0
  - pplacer=1.1.alpha19
  - prank=170427
  - probcons=1.12
  - probconsrna=1.10
  - proda=1.0
  - prodigal=2.6.3
  - pymongo=4.15.3
  - pyparsing=3.2.5
  - pysam=0.22.1
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - quast=5.3.0
  - raxml=8.2.13
  - readline=8.2
  - resfinder=4.7.2
  - rpsbproc=0.5.0
  - sap=1.1.3
  - scipy=1.16.3
  - seqkit=2.10.1
  - setuptools=80.9.0
  - simplejson=3.20.2
  - six=1.17.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - statsmodels=0.14.6
  - t-coffee=13.46.2.7c9e712d
  - tabulate=0.9.0
  - tk=8.6.13
  - tmalign=20170708
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - unzip=6.0
  - viennarna=2.7.0
  - wget=1.21.4
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - geopandas==1.1.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - narwhals==2.10.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygments==2.19.2
      - pyogrio==0.11.1
      - pyproj==3.7.2
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shapely==2.1.2
      - soupsieve==2.8
      - stack-data==0.6.3
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
prefix: /home/kevin/miniconda3/envs/vibrio_env
